version: '3.9'
services:
    api:
        container_name: kunaverso-api
        image: 'nginx:1.23.3-alpine'
        command: nginx -g "daemon off;"
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
            - ./resources/nginx/api.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        container_name: kunaverso-php   
        build: ./resources/8.2
        volumes:
            - '.:/var/www/html'
        ports:
            - '9001:9001'    
        links:
            - mariadb
            - redis
            - mailpit
    mariadb:
        container_name: kunaverso-mariadb
        image: 'mariadb:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes: 
            - db_data:/var/lib/mysql    
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
    redis:
        container_name: kunaverso-redis
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
    mailpit:
        container_name: kunaverso-mailpit
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
volumes:
    db_data: