version: '3.9'
services:
    api:
        container_name: kunaverso-api
        image: 'nginx:1.23.3-alpine'
        command: nginx -g "daemon off;"
        ports:
            - '127.0.0.1:${APP_PORT:-80}:80'
            - '127.0.0.1:${APPS_PORT:-4433}:443'
        volumes:
            - '.:/var/www/html'
            - /etc/letsencrypt/live/api.kunapak.com/fullchain.pem:/etc/letsencrypt/live/api.kunapak.com/fullchain.pem
            - /etc/letsencrypt/live/api.kunapak.com/privkey.pem:/etc/letsencrypt/live/api.kunapak.com/privkey.pem
            - ./resources/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./resources/nginx/api-https.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    php:
        container_name: kunaverso-php
        build: ./resources/8.2
        volumes:
            - '.:/var/www/html'
        ports:
            - '127.0.0.1:9001:9001'    
        links:
            - mariadb
            - redis
    mariadb:
        container_name: kunaverso-mariadb
        image: 'mariadb:latest'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes: 
            - db_data:/var/lib/mysql    
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
    redis:
        container_name: kunaverso-redis
        image: 'redis:alpine'
        ports:
            - '127.0.0.1:${FORWARD_REDIS_PORT:-6379}:6379'
volumes:
    db_data: